# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Install packages without running prepare, then build
RUN npm ci --ignore-scripts && npm run build

# Default command starts the MCP server
CMD ["node", "build/index.js"]
